// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc_E6viIQYet9vf0IOghzCkRUq0SdRyC0',
    appId: '1:161631036735:web:4f5909e1de3daacd429f8a',
    messagingSenderId: '161631036735',
    projectId: 'saudeconecta-58247',
    authDomain: 'saudeconecta-58247.firebaseapp.com',
    storageBucket: 'saudeconecta-58247.appspot.com',
    measurementId: 'G-H6T303YLGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSD5RTSGWKGpUMiLL-ML506nBbiCiTxg',
    appId: '1:161631036735:android:6eb3207d00476d17429f8a',
    messagingSenderId: '161631036735',
    projectId: 'saudeconecta-58247',
    storageBucket: 'saudeconecta-58247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyo4wEgAaGpNaPy7LOxPPhz-ASFWOHg4M',
    appId: '1:161631036735:ios:13bc4edaff48c616429f8a',
    messagingSenderId: '161631036735',
    projectId: 'saudeconecta-58247',
    storageBucket: 'saudeconecta-58247.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyo4wEgAaGpNaPy7LOxPPhz-ASFWOHg4M',
    appId: '1:161631036735:ios:7fefff85dd3d8da7429f8a',
    messagingSenderId: '161631036735',
    projectId: 'saudeconecta-58247',
    storageBucket: 'saudeconecta-58247.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
